### ISSUE TITLE
[Question] Java 11.

### ISSUE THREAD

**Issue by wasdspace** [brucethemoose/Minecraft-Java-Performance-Flags#1]
Hi,
Because of defects of some mods, I can't use Java 17 on 1.16, so I use GraalVM Java 11. Can these arguments for GraalVM Java 8 can be directly used on 11? Or can there be other arguments that can provide additional optimization for 11?
And `-xx:maxgcpausemillis=100` seems to make my game very laggy, which has been significantly improved after I set it to 200 (I also noticed that you edited it just now).
My game has become more perfect due to your arguments, thank you!

**Comment by brucethemoose** [comment]
Yeah, I was just testing that and leaning towards changing maxpausemillis back to the aikar default (along with) G1HeapRegionSize back to 8M).


Anyway, I dunno what flags work on Java 11! The Java 8 flags should work at the very least, but you can probably use  some (if not most or all) of the J17 flags there. Only a few like `UseFMA` may be very new.

**Comment by brucethemoose** [comment]
Also, if you launch Java 11 with the Java 17 flags, most launchers will show what flags they don't like in the log.
