### ISSUE TITLE
Crashes when generating new world

### ISSUE THREAD

**Issue by mangotango69202** [brucethemoose/Minecraft-Java-Performance-Flags#2]
Crashes when generating new world
java version 18.0.1
log 
https://api.mclo.gs/1/raw/FTudBNj

**Comment by brucethemoose** [comment]
Interesting, what CPU are you running?

Try removing these flags: `-XX:+UseAES -XX:+UseAESIntrinsics`, as it crashed right after "[20:39:04] [Server thread/INFO]: Generating keypair"

**Comment by mangotango69202** [comment]
Cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Still crashed when removing `-XX:+UseAES -XX:+UseAESIntrinsics`
flags using `-server -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+UseStringDeduplication -XX:+UseFastUnorderedTimeStamps  -XX:AllocatePrefetchStyle=1 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+UseCodeCacheFlushing -XX:+UseFastJNIAccessors -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+TrustFinalNonStaticFields -XX:ThreadPriorityPolicy=1 -XX:+UseInlineCaches -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseNUMA -XX:-DontCompileHugeMethods -XX:+UseCMoveUnconditionally -XX:+UseFPUForSpilling -XX:+UseNewLongLShift -XX:+UseVectorCmov -XX:+UseXMMForArrayCopy -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+UseXmmLoadAndClearUpper -XX:+UseXmmRegToRegMoveAll -Dfile.encoding=UTF-8 -Djdk.nio.maxCachedBufferSize=262144 -Dgraal.CompilerConfiguration=community -Dgraal.SpeculativeGuardMovement=true --add-modules jdk.incubator.vector -XX:+UseFMA`
new log : https://api.mclo.gs/1/raw/WzBnq2A

**Comment by brucethemoose** [comment]
I've confirmed this crash, narrowing it down now.

**Comment by brucethemoose** [comment]
Figured it out, it was `-XX:+UseCMoveUnconditionally `.

Sorry for not catching this... it must only happen in vanilla?
